### PR TITLE
Add observations

### LINKED ISSUE #4: Implement Observations
Implement the Observations product from Datapoint.

http://www.metoffice.gov.uk/datapoint/product/uk-hourly-site-specific-observations

### PR DESCRIPTION
**Pull request by EJEP**
This follows on from the work done by @leegraham25 in #35, and will close #4.

### CODE REVIEW

**Comment by EJEP** [comment]
@jacobtomlinson do you have a record of how the image of the objects in the documentation (in objects.md) was created? I would like to add the observation class to it for consistency. Thanks

**Comment by jacobtomlinson** [comment]
@EJEP I'm afraid not. I probably used some random web based tool. I'm sure you could quickly recreate it and others in draw.io.

**Comment by EJEP** [comment]
No worries, thanks for the site suggestion

**Comment by EJEP** [comment]
This comment contains the link to the new class diagram:

datapoint_classes

**Comment by EJEP** [comment]
This is now included in the documentation.

**Pull request merged**
