### PR TITLE
Rename forecast site functions

### LINKED ISSUE #75: Tidy functions for sites
At the moment the names of the functions for getting sites are untidy: The ones for observations mention observations in the name; the ones for forecasts don't and therefore appear global.

Tidying this would make it more obvious what the functions do.

### PR DESCRIPTION
**Pull request by EJEP**
Rename forecast site functions to include the word forecast. This removes ambiguity about what the functions do: instead of `get_all_sites()` the function is `get_forecast_sites()` etc..

This is a breaking change so should be included in a version change.

Fixes #75

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Happy to make function names less ambiguous.

A couple of thoughts:
- We could add shims for the old names with a depcrecation warning to maintain backward compatibility.
- The same sites are used for forecasts and observations. Therefore I'm worried that people would look for functions named `get_observation_sites()`.

**Comment by EJEP** [comment]
My intent with the names was to keep the site functions for observations and forecasts seperate, so `get_forecast_sites()` and `get_observation_sites()` rather than one function.

I agree that a deprecation step is a good idea

**Comment by jacobtomlinson** [comment]
My memory may be failing me but do they have different sites?

**Comment by EJEP** [comment]
Yes, there are no where near as many sites for observations as for forecasts.

I haven't checked if the observation sites are also forecast sites.

There is a lot of duplicated code between the functions which could be arranged better - the differences are the API call and the place the data is stored

**Comment by jacobtomlinson** [comment]
Ah fair enough. Then I retract my comment about function names. But backward compatibility would be nice to maintain.

**Comment by jacobtomlinson** [comment]
👍

**Pull request merged**
