### PR TITLE
Add python3 compatability

### PR DESCRIPTION
**Pull request by benjsec**
This makes minor changes that are needed for py3 compatibility

* :type:`long` does not exist in py3, so is aliased to :type:`int` when running under py3
* `StringType` does not exist in py3, instead an `isinstance()` check is used.
* Add `tox.ini` to facilitate testing on both py2 and py3

### CODE REVIEW

**Comment by benjsec** [comment]
The failing tests seem to be travis not having the API_KEY. That being said I hadn't paid enough attention to notice travis, it does make the `tox.ini` a bit redundant except for when running tests locally.

**Comment by jacobtomlinson** [comment]
Thanks for the PR!

Sadly one limitation of Travis is secret environment variables don't work in pull requests. The unit tests seems to have passed though which is all I need to see.

I would appreciate if you could add the version of Python you expect this to work with to the `.travis.yml` file so Travis can unit test against that version. I would also recommend removing `tox.ini` as you say it is redundant.

**Comment by benjsec** [comment]
Thanks for the feedback. I've updated the PR to carry on using travis without tox as requested.

**Comment by jacobtomlinson** [comment]
Looks good. I've manually pulled your branch into a new branch on the main project, this will allow Travis to run the integration tests on it. If all goes well I'll merge it into master.

**Comment by jacobtomlinson** [comment]
I have revisited this in #24. I've taken the minimum changed form your PR and added them in isolation. I would also rather stay away from conda right now.

**Pull request closed without merging**
